global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tf-serving'
    static_configs:
      - targets: ['tf-serving:8501']
    metrics_path: /monitoring/prometheus/metrics
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']