version: '3.7'

services:
  tf-serving:
    image: tensorflow/serving:latest
    container_name: tf_serving_mnist
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ../models/mnist:/models/mnist
      - ../monitoring/monitoring.config.pbtxt:/models/monitoring.config.pbtxt
    environment:
      - MODEL_NAME=mnist
    command: >
      --model_name=mnist
      --model_base_path=/models/mnist
      --monitoring_config_file=/models/monitoring.config.pbtxt
      --rest_api_port=8501
      --port=8500

    restart: unless-stopped
    networks:
      - ml-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=200h'
    restart: unless-stopped
    networks:
      - ml-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - ml-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  ml-network:
    driver: bridge
