name: Weekly Model Retraining

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run retraining pipeline
      run: python scripts/retrain_pipeline.py --min-accuracy 0.97
      
    - name: Deploy if model improved
      if: success()
      run: |
        # Check if new model was promoted
        if grep -q "New model promoted" scripts/retrain_pipeline.py; then
          echo "Deploying new model..."
          docker-compose -f docker/docker-compose.yml restart tf-serving
        else
          echo "No model improvement, skipping deployment"
        fi